In [1]:
import scanpy as sc

In [18]:
adata = sc.read_h5ad("/cs/labs/mornitzan/yam.arieli/datasets/Oelen/1m_scbloodnl_v3.h5ad")

In [21]:
adata.obs

,chemistry,assignment,timepoint,chem,cell_type,cell_type_lowerres
AAACCCAAGATACCAA_190109_lane1,v3,101.0,UT,V3,th2 CD4T,CD4T
AAACCCAAGTCCCTAA_190109_lane1,v3,99.0,3hCA,V3,NKdim,NK
AAACCCACAAGAGTGC_190109_lane1,v3,101.0,UT,V3,naive CD4T,CD4T
AAACCCACAATCCAGT_190109_lane1,v3,101.0,UT,V3,naive CD4T,CD4T
AAACCCACACTATCCC_190109_lane1,v3,99.0,3hCA,V3,mono 1,monocyte
...,...,...,...,...,...,...
TTTGTTGGTGCTTCAA_190205_lane1,v3,49.0,24hCA,V3,memory CD8T left and naive CD8T right,CD8T
TTTGTTGGTGTACAGG_190205_lane1,v3,74.0,24hCA,V3,memory CD8T,CD8T
TTTGTTGGTGTAGCAG_190205_lane1,v3,49.0,24hCA,V3,mono 1,monocyte
TTTGTTGTCCCGTAAA_190205_lane1,v3,95.0,24hCA,V3,th1 CD4T,CD4T
TTTGTTGTCGGTGTAT_190205_lane1,v3,6.0,24hCA,V3,mono 1,monocyte

In [19]:
adata.obs['assignment'] = adata.obs['assignment'].astype(int).astype('category')

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

In [ ]:
adata

AnnData object with n_obs × n_vars = 625677 × 23269
    obs: 'chemistry', 'assignment', 'timepoint', 'chem', 'cell_type', 'cell_type_lowerres'

In [22]:
adata.obs[['assignment', 'timepoint']].drop_duplicates()

                               assignment timepoint
AAACCCAAGATACCAA_190109_lane1       101.0        UT
AAACCCAAGTCCCTAA_190109_lane1        99.0      3hCA
AAACCCACAGGTACGA_190109_lane1        97.0        UT
AAACCCATCAACTGAC_190109_lane1        94.0      3hCA
AAACCCATCGCTGTTC_190109_lane1        98.0        UT
...                                   ...       ...
AAACCCAGTCCGGATC_190205_lane1        43.0     24hCA
AAACCCAGTGAATTAG_190205_lane1        10.0     24hCA
AAACCCATCCATCCGT_190205_lane1        95.0     24hCA
AAACGAAAGGCCTGCT_190205_lane1         6.0     24hCA
AAACGCTCACCAACAT_190205_lane1        19.0     24hCA

[241 rows x 2 columns]

In [23]:
adata.X[10100:10110, 1000:1010].toarray()

array([[0., 0., 0., 0., 0., 0., 0., 0., 2., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)